### ISSUE TITLE
Fetch villages data from Wikipedia and WikiData

### ISSUE THREAD

**Issue by macbre** [macbre/faroese-resources#1]
* [x] get the list of all pages on English Wikipedia
* [x] fetch all pages and get their WikiData ID and interwiki links (https://github.com/macbre/nodemw/pull/345)
* [x] parse content of various translations (https://github.com/macbre/nodemw/issues/346)
* [x] get IPA pronunciation, geo data (https://github.com/macbre/nodemw/issues/346)

## API endpoints

* https://en.wikipedia.org/w/api.php?action=query&format=json&redirects=1&titles=Saksun&prop=pageprops -> get WikiData ID
* https://www.wikidata.org/w/api.php?action=wbgetentities&sites=enwiki&titles=Saksun&normalize=&props=sitelinks - links to other languages
* https://www.wikidata.org/w/api.php?action=query&prop=pageprops&titles=Q928875
* https://www.wikidata.org/w/api.php?action=wbgetclaims&entity=Q928875&format=json

## WikiData entries

https://www.wikidata.org/wiki/Q928875

* P625 - https://www.wikidata.org/wiki/Property:P625 (geo location)
* P1082 - https://www.wikidata.org/wiki/Property:P1082 (population)

```yaml
# $ curl -s 'https://www.wikidata.org/w/api.php?action=wbgetclaims&entity=Q928875&format=json' | jq .claims.P625[0].mainsnak       
{
  "snaktype": "value",
  "property": "P625",
  "hash": "ee74ea81115d83fe54be3bea8904f782682fd638",
  "datavalue": {
    "value": {
      "latitude": 62.248888888889,
      "longitude": -7.1758333333333,
      "altitude": null,
      "precision": 0.00027777777777778,
      "globe": "http://www.wikidata.org/entity/Q2"
    },
    "type": "globecoordinate"
  },
  "datatype": "globe-coordinate"
}
```
